# Generated by Django 4.1.7 on 2023-03-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_band_clothings_band_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
