# Generated by Django 4.1.7 on 2023-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='version',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
